### ISSUE TITLE
Dependency Hell...

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/honeybee-radiance#43]
Made a small change to the build [here](5807ccae94e9ecdd568cb9cab4af734143c57553) and tests have failed. I suspect this is because of certain dependencies changing leading to failing tests.

Here are the versions for the [working build](https://travis-ci.org/github/ladybug-tools/honeybee-radiance/jobs/654615371#L301) and here are the ones for the [failing build](https://travis-ci.org/github/ladybug-tools/honeybee-radiance/jobs/666610283#L297).

The key differences are:
* ladybug-geometry: 1.14.0 - 1.18.1
* lbt-ladybug: 0.16 - 0.21.1

This package however only has the following dependencies:
```
honeybee-core>=1.10.0
honeybee-radiance-command>=1.0.0
```

Only `honeybee-core` depends on ladybug:
```
lbt-ladybug>=0.4.3
```

Not sure what the best way resolving this is but here are some solutions:
1. Set hard dependency versions in this repo (ie: figure out which version of honeybee-core works and stick to that)
2. Set hard dependency versions **everywhere** so that any changes are deliberate and tested with more ease/reproducibility before being pushed to master
3. Fix upstream bugs in ladybug that are causing this package to fail

Thoughts @mostaphaRoudsari @chriswmackey and @saeranv?

**Comment by mostaphaRoudsari** [comment]
This is because of the recent fix in sunpath in ladybug. Chris has made sure that the local time doesn't get overwritten. That's why the number of up sun positions are different from what we expected them to be originally in tests.

Setting hard dependency won't solve the problem as it will break other libraries which have dependencies on a different version. We should be flexible enough to let everyone use the version 0.x.y.

What I have seen people do with npm packages is to create a new PR whenever one of the dependencies are updated with the updated dependency. That will trigger a built which will show issues like this. Then we can make a decision on how to address the issue if there is any. https://greenkeeper.io/

I don't think we can automate this everywhere (or maybe we can?) but we should be able to write certain workflows for our ladybug-tools libraries. Or is there a similar service to `greenkeeper` that we should just use instead?

**Comment by mostaphaRoudsari** [comment]
Here we go! https://dependabot.com/python/

It's acquired by GitHub and is now free. I remember I suggested using this before but @AntoineDao was afraid we will end up with a lot of PRs on a daily basis based on his experience from his previous job. :) I think the difference here is we are not using npm and we don't have as many dependencies so it should be manageable. And from what we see happening it is somewhat required.

**Comment by mostaphaRoudsari** [comment]
Look at that! =D

![image](https://user-images.githubusercontent.com/2915573/78790914-311bcd80-797d-11ea-8ffe-90cdefe13711.png)
