### ISSUE TITLE
BSDF dictionary is not JSON serializable

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-radiance#67]
Given the way that the BSDF file is serialized to a dictionary, it cannot be written to a JSON format or converted to a string in Python 3.  The following test code:
```
import json

relative_path = './tests/assets/klemsfull.xml'
klemsfull = BSDF(relative_path)
json.dumps(klemsfull.to_dict(), indent=4)
```

... results in the following error:
`TypeError: Object of type bytes is not JSON serializable`

I'm not sure what you would suggest to deal with this here, @mostaphaRoudsari .

**Comment by mostaphaRoudsari** [comment]
The root of the issue is how we are compressing the data to bytes.

https://github.com/ladybug-tools/honeybee-radiance/blob/77302ab21d9c09663c1e2ba64340e30b3bb75dc1/honeybee_radiance/modifier/material/bsdf.py#L468-L478

We should look into solutions that generates string like objects that can be serialized I guess. I have to do some search about this as I really don't know the answer for what can be the best solution. The first easy test is to change the mode in those methods from `rb` and `wb` to `r` and `w` and see if that resolves this issue.

**Comment by chriswmackey** [comment]
Ok. I will give that a try.

**Comment by chriswmackey** [comment]
It looks like gzip exclusively compresses and decompresses things to bytes and not strings (I get an error from gzip if I don't read the file in as bytes). Should we just abandon the use of gzip for now and store the XML data as a string?  The alternative seems to be to just not support BSDFs in any schema or pollination workflows for now.

**Comment by mostaphaRoudsari** [comment]
That's unfortunate. Let me give it a quick try and let you know if I find a solution otherwise using string looks like a good way to fix this for now.

**Comment by mostaphaRoudsari** [comment]
Hey @chriswmackey, I will not have the time to check this issue right now. Let's go ahead with your suggestion of using string and if it becomes an issue in the future we can revisit it. It will be nice if we can remove the whitespaces in the file to keep it smaller e.g `content = ' '.join(content.split())`

**Comment by chriswmackey** [comment]
Thank you for giving it a shot, @mostaphaRoudsari .  I'm knee deep into the dynamic geometry PR at the moment but I will implement the string option minus whitespaces after that's done.

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/honeybee-radiance/pull/78
